return {
	["Actor"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["AdGui"] = {
		{ "FallbackImageContent", "ContentId" },
	},
	["AlignOrientation"] = {
		{ "PrimaryAxis", "Vector3" },
		{ "SecondaryAxis", "Vector3" },
		{ "LookAtPosition", "Vector3" },
	},
	["Animation"] = {
		{ "AnimationContent", "ContentId" },
	},
	["AnimationTrack"] = {
		{ "Looped", "Bool" },
		{ "TimePosition", "Float32" },
	},
	["Attachment"] = {
		{ "Axis", "Vector3" },
		{ "SecondaryAxis", "Vector3" },
		{ "WorldAxis", "Vector3" },
		{ "WorldSecondaryAxis", "Vector3" },
		{ "WorldCFrame", "CFrame" },
	},
	["BackpackItem"] = {
		{ "TextureContent", "ContentId" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["BallSocketConstraint"] = {
		{ "MaxFrictionTorque", "Float32" },
	},
	["BasePart"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["BaseScript"] = {
		{ "Enabled", "Bool" },
	},
	["BaseWrap"] = {
		{ "CageMeshContent", "ContentId" },
	},
	["Beam"] = {
		{ "TextureContent", "ContentId" },
	},
	["BillboardGui"] = {
		{ "DistanceStep", "Float32" },
	},
	["BodyColors"] = {
		{ "HeadColor", "BrickColor" },
		{ "LeftArmColor", "BrickColor" },
		{ "LeftLegColor", "BrickColor" },
		{ "RightArmColor", "BrickColor" },
		{ "RightLegColor", "BrickColor" },
		{ "TorsoColor", "BrickColor" },
	},
	["Bone"] = {
		{ "Axis", "Vector3" },
		{ "SecondaryAxis", "Vector3" },
		{ "WorldAxis", "Vector3" },
		{ "WorldSecondaryAxis", "Vector3" },
		{ "WorldCFrame", "CFrame" },
		{ "Transform", "CFrame" },
	},
	["BubbleChatMessageProperties"] = {
		{ "BackgroundColor3", "Color3" },
		{ "BackgroundTransparency", "Float64" },
		{ "FontFace", "Font" },
		{ "TextColor3", "Color3" },
		{ "TextSize", "Int64" },
		{ "TailVisible", "Bool" },
		{ "PrefixText", "String" },
		{ "Text", "String" },
		{ "Translation", "String" },
	},
	["Camera"] = {
		{ "DiagonalFieldOfView", "Float32" },
		{ "MaxAxisFieldOfView", "Float32" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["CharacterMesh"] = {
		{ "BaseTextureContent", "ContentId" },
		{ "OverlayTextureContent", "ContentId" },
		{ "MeshContent", "ContentId" },
	},
	["ChatInputBarConfiguration"] = {
		{ "TextBox", "Ref" },
	},
	["ChatWindowMessageProperties"] = {
		{ "FontFace", "Font" },
		{ "PrefixTextProperties", "Ref" },
		{ "TextColor3", "Color3" },
		{ "TextSize", "Int32" },
		{ "TextStrokeColor3", "Color3" },
		{ "TextStrokeTransparency", "Float64" },
		{ "PrefixText", "String" },
		{ "Text", "String" },
		{ "Translation", "String" },
	},
	["ClickDetector"] = {
		{ "CursorIconContent", "ContentId" },
	},
	["CoreScript"] = {
		{ "Enabled", "Bool" },
	},
	["CornerWedgePart"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Decal"] = {
		{ "NormalMapContent", "ContentId" },
		{ "ColorMapContent", "ContentId" },
		{ "MetalnessMapContent", "ContentId" },
		{ "RoughnessMapContent", "ContentId" },
		{ "TextureContent", "ContentId" },
	},
	["DeviceDisplayService"] = {
		{ "Archivable", "Bool" },
	},
	["Dialog"] = {
		{ "InUse", "Bool" },
	},
	["DisplayWakeLock"] = {
		{ "Archivable", "Bool" },
	},
	["DragDetector"] = {
		{ "Axis", "Vector3" },
		{ "WorldAxis", "Vector3" },
		{ "WorldSecondaryAxis", "Vector3" },
		{ "SecondaryAxis", "Vector3" },
		{ "ActivatedCursorIconContent", "ContentId" },
		{ "CursorIconContent", "ContentId" },
	},
	["DraggerService"] = {
		{ "AlignDraggedObjects", "Bool" },
		{ "AngleSnapEnabled", "Bool" },
		{ "AngleSnapIncrement", "Float32" },
		{ "AnimateHover", "Bool" },
		{ "CollisionsEnabled", "Bool" },
		{ "DraggerCoordinateSpace", "Enum.DraggerCoordinateSpace" },
		{ "DraggerMovementMode", "Enum.DraggerMovementMode" },
		{ "GeometrySnapColor", "Color3" },
		{ "HoverAnimateFrequency", "Float32" },
		{ "HoverThickness", "Float32" },
		{ "JointsEnabled", "Bool" },
		{ "LinearSnapEnabled", "Bool" },
		{ "LinearSnapIncrement", "Float32" },
		{ "ShowHover", "Bool" },
		{ "ShowPivotIndicator", "Bool" },
	},
	["EditorSourceService"] = {
		{ "Archivable", "Bool" },
	},
	["FaceControls"] = {
		{ "Corrugator", "Float32" },
		{ "LeftNoseWrinkler", "Float32" },
		{ "LeftBrowLowerer", "Float32" },
		{ "LeftInnerBrowRaiser", "Float32" },
		{ "LeftOuterBrowRaiser", "Float32" },
		{ "RightBrowLowerer", "Float32" },
		{ "RightInnerBrowRaiser", "Float32" },
		{ "RightNoseWrinkler", "Float32" },
		{ "RightOuterBrowRaiser", "Float32" },
		{ "EyesLookDown", "Float32" },
		{ "EyesLookRight", "Float32" },
		{ "LeftCheekRaiser", "Float32" },
		{ "LeftEyeUpperLidRaiser", "Float32" },
		{ "EyesLookLeft", "Float32" },
		{ "EyesLookUp", "Float32" },
		{ "LeftEyeClosed", "Float32" },
		{ "RightCheekRaiser", "Float32" },
		{ "RightEyeClosed", "Float32" },
		{ "RightEyeUpperLidRaiser", "Float32" },
		{ "JawRight", "Float32" },
		{ "JawDrop", "Float32" },
		{ "JawLeft", "Float32" },
		{ "ChinRaiser", "Float32" },
		{ "Funneler", "Float32" },
		{ "ChinRaiserUpperLip", "Float32" },
		{ "FlatPucker", "Float32" },
		{ "LeftCheekPuff", "Float32" },
		{ "LeftDimpler", "Float32" },
		{ "LeftLipCornerDown", "Float32" },
		{ "LeftLipCornerPuller", "Float32" },
		{ "LeftLipStretcher", "Float32" },
		{ "LeftLowerLipDepressor", "Float32" },
		{ "LeftUpperLipRaiser", "Float32" },
		{ "LipPresser", "Float32" },
		{ "LipsTogether", "Float32" },
		{ "LowerLipSuck", "Float32" },
		{ "MouthLeft", "Float32" },
		{ "MouthRight", "Float32" },
		{ "Pucker", "Float32" },
		{ "RightCheekPuff", "Float32" },
		{ "RightDimpler", "Float32" },
		{ "RightLipCornerDown", "Float32" },
		{ "RightLipCornerPuller", "Float32" },
		{ "RightLipStretcher", "Float32" },
		{ "RightLowerLipDepressor", "Float32" },
		{ "RightUpperLipRaiser", "Float32" },
		{ "UpperLipSuck", "Float32" },
		{ "TongueDown", "Float32" },
		{ "TongueOut", "Float32" },
		{ "TongueUp", "Float32" },
	},
	["FileMesh"] = {
		{ "MeshContent", "ContentId" },
		{ "TextureContent", "ContentId" },
	},
	["Flag"] = {
		{ "TextureContent", "ContentId" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["FlagStand"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["FormFactorPart"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["GuiService"] = {
		{ "TouchControlsEnabled", "Bool" },
	},
	["HopperBin"] = {
		{ "TextureContent", "ContentId" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Humanoid"] = {
		{ "Sit", "Bool" },
		{ "Jump", "Bool" },
		{ "PlatformStand", "Bool" },
		{ "TargetPoint", "Vector3" },
		{ "WalkToPart", "Ref" },
		{ "WalkToPoint", "Vector3" },
		{ "CameraOffset", "Vector3" },
		{ "Health", "Float32" },
	},
	["HumanoidDescription"] = {
		{ "AccessoryBlob", "String" },
		{ "BackAccessory", "String" },
		{ "FaceAccessory", "String" },
		{ "FrontAccessory", "String" },
		{ "HatAccessory", "String" },
		{ "HairAccessory", "String" },
		{ "NeckAccessory", "String" },
		{ "ShouldersAccessory", "String" },
		{ "WaistAccessory", "String" },
		{ "LeftArmColor", "Color3" },
		{ "LeftLegColor", "Color3" },
		{ "HeadColor", "Color3" },
		{ "RightArmColor", "Color3" },
		{ "RightLegColor", "Color3" },
		{ "TorsoColor", "Color3" },
		{ "LeftArm", "Int64" },
		{ "LeftLeg", "Int64" },
		{ "Head", "Int64" },
		{ "RightArm", "Int64" },
		{ "RightLeg", "Int64" },
		{ "Torso", "Int64" },
	},
	["ImageButton"] = {
		{ "ImageContent", "ContentId" },
		{ "HoverImageContent", "ContentId" },
		{ "PressedImageContent", "ContentId" },
	},
	["ImageHandleAdornment"] = {
		{ "ImageContent", "ContentId" },
	},
	["ImageLabel"] = {
		{ "ImageContent", "ContentId" },
	},
	["InputBinding"] = {
		{ "DisplayImage", "ContentId" },
		{ "DisplayName", "String" },
	},
	["InputObject"] = {
		{ "KeyCode", "Enum.KeyCode" },
		{ "Position", "Vector3" },
		{ "UserInputType", "Enum.UserInputType" },
		{ "Delta", "Vector3" },
		{ "UserInputState", "Enum.UserInputState" },
	},
	["IntersectOperation"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "FluidFidelity", "Enum.FluidFidelity" },
		{ "CollisionFidelity", "Enum.CollisionFidelity" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["LocalScript"] = {
		{ "Enabled", "Bool" },
	},
	["MaterialVariant"] = {
		{ "EmissiveMaskContent", "ContentId" },
		{ "NormalMapContent", "ContentId" },
		{ "ColorMapContent", "ContentId" },
		{ "MetalnessMapContent", "ContentId" },
		{ "RoughnessMapContent", "ContentId" },
	},
	["MeshPart"] = {
		{ "TextureContent", "ContentId" },
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "FluidFidelity", "Enum.FluidFidelity" },
		{ "CollisionFidelity", "Enum.CollisionFidelity" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Model"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Motor"] = {
		{ "CurrentAngle", "Float32" },
	},
	["Motor6D"] = {
		{ "CurrentAngle", "Float32" },
	},
	["Mouse"] = {
		{ "IconContent", "ContentId" },
	},
	["NegateOperation"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "FluidFidelity", "Enum.FluidFidelity" },
		{ "CollisionFidelity", "Enum.CollisionFidelity" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Pants"] = {
		{ "PantsTemplateContent", "ContentId" },
	},
	["Part"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["ParticleEmitter"] = {
		{ "TextureContent", "ContentId" },
	},
	["PartOperation"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "FluidFidelity", "Enum.FluidFidelity" },
		{ "CollisionFidelity", "Enum.CollisionFidelity" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Platform"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Player"] = {
		{ "CanLoadCharacterAppearance", "Bool" },
		{ "DisplayName", "String" },
		{ "HasVerifiedBadge", "Bool" },
		{ "UserId", "Int64" },
	},
	["PlayerMouse"] = {
		{ "IconContent", "ContentId" },
	},
	["PluginMenu"] = {
		{ "Title", "String" },
		{ "Icon", "String" },
	},
	["PluginMouse"] = {
		{ "IconContent", "ContentId" },
	},
	["PluginToolbarButton"] = {
		{ "ClickableWhenViewportHidden", "Bool" },
		{ "Enabled", "Bool" },
		{ "Icon", "ContentId" },
		{ "IconContent", "ContentId" },
	},
	["PopLatencyService"] = {
		{ "Archivable", "Bool" },
	},
	["ProceduralModel"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["PVInstance"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["RunService"] = {
		{ "RunState", "Enum.RunState" },
	},
	["ScreenshotHud"] = {
		{ "CameraButtonIconContent", "ContentId" },
	},
	["Script"] = {
		{ "Enabled", "Bool" },
	},
	["ScrollingFrame"] = {
		{ "MidImageContent", "ContentId" },
		{ "BottomImageContent", "ContentId" },
		{ "TopImageContent", "ContentId" },
	},
	["Seat"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Shirt"] = {
		{ "ShirtTemplateContent", "ContentId" },
	},
	["ShirtGraphic"] = {
		{ "TextureContent", "ContentId" },
	},
	["SkateboardPlatform"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Sky"] = {
		{ "MoonTextureContent", "ContentId" },
		{ "SkyboxFrontContent", "ContentId" },
		{ "SkyboxBackContent", "ContentId" },
		{ "SkyboxDownContent", "ContentId" },
		{ "SkyboxLeftContent", "ContentId" },
		{ "SkyboxRightContent", "ContentId" },
		{ "SkyboxUpContent", "ContentId" },
		{ "SunTextureContent", "ContentId" },
	},
	["SpawnLocation"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["SpecialMesh"] = {
		{ "MeshContent", "ContentId" },
		{ "TextureContent", "ContentId" },
	},
	["Status"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Studio"] = {
		{ "PluginsDir", "QDir" },
		{ "Output Font", "QFont" },
		{ "Font", "QFont" },
		{ "\"TODO\" Color", "Color3" },
		{ "TypeColor", "Color3" },
		{ "\"function\" Color", "Color3" },
		{ "\"local\" Color", "Color3" },
		{ "\"self\" Color", "Color3" },
		{ "Background Color", "Color3" },
		{ "Bool Color", "Color3" },
		{ "Bracket Color", "Color3" },
		{ "Built-in Function Color", "Color3" },
		{ "Comment Color", "Color3" },
		{ "Current Line Highlight Color", "Color3" },
		{ "Debugger Current Line Color", "Color3" },
		{ "Debugger Error Line Color", "Color3" },
		{ "Function Name Color", "Color3" },
		{ "\"nil\" Color", "Color3" },
		{ "Error Color", "Color3" },
		{ "Find Selection Background Color", "Color3" },
		{ "HintColor", "Color3" },
		{ "InformationColor", "Color3" },
		{ "Keyword Color", "Color3" },
		{ "Luau Keyword Color", "Color3" },
		{ "Matching Word Background Color", "Color3" },
		{ "Menu Item Background Color", "Color3" },
		{ "Method Color", "Color3" },
		{ "Number Color", "Color3" },
		{ "Operator Color", "Color3" },
		{ "Primary Text Color", "Color3" },
		{ "Property Color", "Color3" },
		{ "Ruler Color", "Color3" },
		{ "Script Editor Scrollbar Background Color", "Color3" },
		{ "Script Editor Scrollbar Handle Color", "Color3" },
		{ "Secondary Text Color", "Color3" },
		{ "Selected Menu Item Background Color", "Color3" },
		{ "Selected Text Color", "Color3" },
		{ "Selection Background Color", "Color3" },
		{ "Selection Color", "Color3" },
		{ "String Color", "Color3" },
		{ "Text Color", "Color3" },
		{ "Warning Color", "Color3" },
		{ "Whitespace Color", "Color3" },
	},
	["StudioService"] = {
		{ "UseLocalSpace", "Bool" },
	},
	["StyleQuery"] = {
		{ "ViewportDisplaySize", "Enum.DisplaySize" },
		{ "AspectRatioRange", "NumberRange" },
		{ "MaxSize", "Vector2" },
		{ "MinSize", "Vector2" },
		{ "ReducedMotionEnabled", "Bool" },
		{ "PreferredTextSize", "Enum.PreferredTextSize" },
		{ "PreferredInput", "Enum.PreferredInput" },
	},
	["SurfaceAppearance"] = {
		{ "EmissiveMaskContent", "ContentId" },
	},
	["Terrain"] = {
		{ "MaterialColors", "BinaryString" },
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["TerrainDetail"] = {
		{ "EmissiveMaskContent", "ContentId" },
		{ "ColorMapContent", "ContentId" },
		{ "MetalnessMapContent", "ContentId" },
		{ "RoughnessMapContent", "ContentId" },
		{ "NormalMapContent", "ContentId" },
	},
	["TextBox"] = {
		{ "CursorPosition", "Int32" },
		{ "SelectionStart", "Int32" },
	},
	["TextChatMessage"] = {
		{ "MessageId", "String" },
		{ "Metadata", "String" },
		{ "PrefixText", "String" },
		{ "Status", "Enum.TextChatMessageStatus" },
		{ "Text", "String" },
		{ "Timestamp", "DateTime" },
		{ "Translation", "String" },
	},
	["TextChatMessageProperties"] = {
		{ "PrefixText", "String" },
		{ "Text", "String" },
		{ "Translation", "String" },
	},
	["Texture"] = {
		{ "NormalMapContent", "ContentId" },
		{ "ColorMapContent", "ContentId" },
		{ "MetalnessMapContent", "ContentId" },
		{ "RoughnessMapContent", "ContentId" },
		{ "TextureContent", "ContentId" },
	},
	["Tool"] = {
		{ "TextureContent", "ContentId" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["Trail"] = {
		{ "TextureContent", "ContentId" },
	},
	["TriangleMeshPart"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "FluidFidelity", "Enum.FluidFidelity" },
		{ "CollisionFidelity", "Enum.CollisionFidelity" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["TrussPart"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Style", "Enum.Style" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["UIDragDetector"] = {
		{ "ActivatedCursorIconContent", "ContentId" },
		{ "CursorIconContent", "ContentId" },
	},
	["UnionOperation"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "FluidFidelity", "Enum.FluidFidelity" },
		{ "CollisionFidelity", "Enum.CollisionFidelity" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["UserGameSettings"] = {
		{ "RotationType", "Enum.RotationType" },
	},
	["UserInputService"] = {
		{ "MouseDeltaSensitivity", "Float32" },
		{ "MouseIconContent", "ContentId" },
	},
	["VehicleSeat"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["VideoFrame"] = {
		{ "VideoContent", "ContentId" },
	},
	["VideoPlayer"] = {
		{ "VideoContent", "ContentId" },
	},
	["ViewportFrame"] = {
		{ "CurrentCamera", "Ref" },
	},
	["VRService"] = {
		{ "GuiInputUserCFrame", "Enum.UserCFrame" },
	},
	["WedgePart"] = {
		{ "AssemblyLinearVelocity", "Vector3" },
		{ "AssemblyAngularVelocity", "Vector3" },
		{ "Rotation", "Vector3" },
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["WeldConstraint"] = {
		{ "Enabled", "Bool" },
	},
	["Workspace"] = {
		{ "InsertPoint", "Vector3" },
		{ "PredictiveStreamingMode", "Enum.PredictiveStreamingMode" },
	},
	["WorldModel"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["WorldRoot"] = {
		{ "Pivot Offset", "CFrame" },
		{ "Origin", "CFrame" },
	},
	["WrapDeformer"] = {
		{ "CageMeshContent", "ContentId" },
	},
	["WrapLayer"] = {
		{ "CageMeshContent", "ContentId" },
		{ "ReferenceMeshContent", "ContentId" },
		{ "Color", "Color3" },
		{ "DebugMode", "Enum.WrapLayerDebugMode" },
	},
	["WrapTarget"] = {
		{ "CageMeshContent", "ContentId" },
		{ "Color", "Color3" },
		{ "DebugMode", "Enum.WrapTargetDebugMode" },
	},
	["WrapTextureTransfer"] = {
		{ "ReferenceCageMeshContent", "ContentId" },
	},
}
