pub(super) const COMMAND_EXAMPLES: &[(&str, &str)] = &[
    ("fmt", "Examples:\n  rbx fmt ."),
    ("pv", "Examples:\n  rbx pv"),
    ("xp", "Examples:\n  rbx xp src/Workspace/Door"),
    ("cfg", "Examples:\n  rbx cfg list"),
    ("ad", "Examples:\n  rbx ad validate"),
    ("ir", "Examples:\n  rbx ir --project default.project.json"),
    ("init", "Examples:\n  rbx init ."),
    ("build", "Examples:\n  rbx build"),
    ("dr", "Examples:\n  rbx dr"),
    ("docs", "Examples:\n  rbx docs sync"),
    ("dm", "Examples:\n  rbx dm list"),
    ("so", "Examples:\n  rbx so Place.rbxl"),
    ("ro", "Examples:\n  rbx ro Place.rbxl"),
    ("sx", "Examples:\n  rbx sx --save"),
    ("status", "Examples:\n  rbx status --all"),
    (
        "up",
        "Examples:\n  rbx up --place-id 123456 --universe-id 654321",
    ),
    ("upd", "Examples:\n  rbx upd"),
    ("oc", "Examples:\n  rbx oc key"),
    ("sb", "Examples:\n  rbx sb --dry-run"),
    (
        "ip",
        "Examples:\n  rbx ip car.rbxm --destination ServerStorage.Cars",
    ),
    (
        "cr",
        "Examples:\n  rbx cr Workspace --class-name Part --name Door",
    ),
    (
        "cp",
        "Examples:\n  rbx cp Workspace --settings-id editor:source --parent-settings-id editor:parent",
    ),
    (
        "mv",
        "Examples:\n  rbx mv Workspace --settings-id editor:item --parent-settings-id editor:parent",
    ),
    (
        "rn",
        "Examples:\n  rbx rn Workspace Door --settings-id editor:item",
    ),
    (
        "rm",
        "Examples:\n  rbx rm Workspace --settings-id editor:item",
    ),
    (
        "dpl",
        "Examples:\n  rbx dpl ReplicatedStorage --settings-id editor:package",
    ),
    (
        "mip",
        "Examples:\n  rbx mip ReplicatedStorage --parent-settings-id editor:parent --model car.rbxm",
    ),
    (
        "mep",
        "Examples:\n  rbx mep Workspace --settings-id editor:model --output model.rbxm",
    ),
    ("tst", "Examples:\n  rbx tst --mode play --timeout 30"),
    ("x", "Examples:\n  rbx x --snapshot-dir snapshots"),
    ("pl", "Examples:\n  rbx pl"),
    ("bd", "Examples:\n  rbx bd"),
    ("ed", "Examples:\n  rbx ed"),
    (
        "src",
        "Examples:\n  rbx src --service ServerScriptService --source-key editor:script",
    ),
    ("co", "Examples:\n  rbx co --player 1 --limit 20"),
    ("l", "Examples:\n  rbx l \"return game.PlaceId\""),
    ("lc", "Examples:\n  rbx lc \"return game.PlaceId\" 1"),
    ("dev", "Examples:\n  rbx dev set \"iPhone 16 Pro\""),
    ("as", "Examples:\n  rbx as \"sports car\" --limit 10"),
    ("ai", "Examples:\n  rbx ai 123456789"),
    ("gm", "Examples:\n  rbx gm \"small wooden cabin\""),
    ("js", "Examples:\n  rbx js job-id --wait-seconds 30"),
    ("is", "Examples:\n  rbx is icon.png"),
    ("iu", "Examples:\n  rbx iu icon.png --user 123456"),
    ("ss", "Examples:\n  rbx ss DataStore UpdateAsync"),
    ("sg", "Examples:\n  rbx sg \"DailyReward\""),
    (
        "sr",
        "Examples:\n  rbx sr src/ServerScriptService/Main.server.luau",
    ),
    ("play", "Examples:\n  rbx play\n  rbx play -x"),
    ("cs", "Examples:\n  rbx cs"),
    ("rv", "Examples:\n  rbx rv apply"),
    ("pr", "Examples:\n  rbx pr \"Shop.BuyButton\" -p 1"),
    ("clk", "Examples:\n  rbx clk 450 320 -p 1"),
    ("ky", "Examples:\n  rbx ky E -p 1"),
    ("ui", "Examples:\n  rbx ui -p 1"),
    (
        "ty",
        "Examples:\n  rbx ty \"hello\" --path \"Chat.Box\" --enter -p 1",
    ),
    (
        "wait",
        "Examples:\n  rbx wait \"workspace:GetAttribute('Ready') ~= nil\" -c -t 20",
    ),
    ("go", "Examples:\n  rbx go \"Workspace.Shop.Door\" -p 1"),
    ("sc", "Examples:\n  rbx sc --studio -o studio.png"),
    (
        "inp",
        "Examples:\n  rbx inp -p 1 click \"Shop.BuyButton\" wait 100 key E",
    ),
    ("rs", "Examples:\n  rbx rs -o playtest.mp4"),
    ("re", "Examples:\n  rbx re"),
    ("setup", "Examples:\n  rbx setup"),
    ("st", "Examples:\n  rbx st --event-wait-seconds 1"),
    ("lon", "Examples:\n  rbx lon"),
    ("lof", "Examples:\n  rbx lof"),
    ("lst", "Examples:\n  rbx lst"),
    ("rp", "Examples:\n  rbx rp"),
    ("dp", "Examples:\n  rbx dp"),
    (
        "ps",
        "Examples:\n  rbx ps --changed-path src/StarterGui/Menu.client.luau",
    ),
    (
        "prop",
        "Examples:\n  rbx prop --service Workspace --path-segments-json '[\"Door\"]' --property Name --value-json '\"Gate\"'",
    ),
    (
        "del",
        "Examples:\n  rbx del --service Workspace --path-segments-json '[\"TemporaryPart\"]'",
    ),
    (
        "rev",
        "Examples:\n  rbx rev --service Workspace --settings-id editor:item",
    ),
    (
        "me",
        "Examples:\n  rbx me src/ServerScriptService/Main.server.luau oldName newName",
    ),
    ("f", "Examples:\n  rbx f Workspace -n Door --limit 5"),
    ("tr", "Examples:\n  rbx tr Workspace Door --depth 2"),
    ("in", "Examples:\n  rbx in Workspace -i editor:item"),
    ("bg", "Examples:\n  rbx bg Workspace -i editor:item -p Name"),
    (
        "bs",
        "Examples:\n  rbx bs Workspace -i editor:item -p Name --str Gate",
    ),
    (
        "bss",
        "Examples:\n  rbx bss ServerScriptService -i editor:script --str \"print('hello')\"",
    ),
    (
        "bb",
        "Examples:\n  rbx bb Workspace -j '{\"ops\":[{\"type\":\"counts\"}]}'",
    ),
    ("bt", "Examples:\n  rbx bt --services Workspace,StarterGui"),
    (
        "ba",
        "Examples:\n  rbx ba Workspace -n Door -c Part -I editor:parent",
    ),
    (
        "bcl",
        "Examples:\n  rbx bcl Workspace -i editor:source -I editor:parent",
    ),
    ("br", "Examples:\n  rbx br Workspace -i editor:item"),
    (
        "bdp",
        "Examples:\n  rbx bdp ReplicatedStorage -i editor:package",
    ),
    (
        "bem",
        "Examples:\n  rbx bem Workspace -i editor:model -o model.rbxm",
    ),
    ("bep", "Examples:\n  rbx bep -o place.rbxl"),
    (
        "pdp",
        "Examples:\n  rbx pdp -i place.rbxl -o copy.rbxl --path '[\"Workspace\",\"Model\"]'",
    ),
    (
        "bim",
        "Examples:\n  rbx bim ReplicatedStorage --model model.rbxm -I editor:parent",
    ),
    ("wally", "Examples:\n  rbx wally"),
    ("lk", "Examples:\n  rbx lk"),
    ("lkb", "Examples:\n  rbx lkb --link shared-module"),
    ("lks", "Examples:\n  rbx lks"),
    (
        "lka",
        "Examples:\n  rbx lka --service ReplicatedStorage --path '[\"Shared\"]' --source src/Shared.luau",
    ),
    (
        "lkp",
        "Examples:\n  rbx lkp --service ReplicatedStorage --path '[\"Vehicles\",\"Car\"]'",
    ),
    ("lkd", "Examples:\n  rbx lkd --id shared-module"),
    (
        "bpack",
        "Examples:\n  rbx bpack Workspace ReplicatedStorage",
    ),
    (
        "si",
        "Examples:\n  rbx si --snapshot-dir snapshots --project-root .",
    ),
    (
        "ims",
        "Examples:\n  rbx ims --project-root . --service Workspace",
    ),
    ("sm", "Examples:\n  rbx sm -o sourcemap.json"),
    ("vci", "Examples:\n  rbx vci"),
    ("vct", "Examples:\n  rbx vct src/Workspace.renium"),
    ("v", "Examples:\n  rbx v model.rbxm --json"),
    (
        "vcm",
        "Examples:\n  rbx vcm base.renium ours.renium theirs.renium --output merged.renium",
    ),
    (
        "pa",
        "Examples:\n  rbx pa 123456 \"Lobby\" --game-id 654321 --alias lobby",
    ),
    ("pn", "Examples:\n  rbx pn 123456 main"),
    ("po", "Examples:\n  rbx po 123456 789012"),
];
